compute_environment: LOCAL_MACHINE
deepseed_config: null
distributed_type: MULTI_CPU
fsdp_config: null
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
use_cpu: true
